Repository smoia/phys2cvr, pull requests merged in 2021-11, with the labels that each got.

#27 If scale factor is declared, *divide* the betas by the scale factor
  phys2cvr/cli/run.py
  phys2cvr/phys2cvr.py
Labels: Minormod-breaking

#28 Fix peak array loading for index purposes
  phys2cvr/phys2cvr.py
Labels: BugFIX

#29 Fix scale factor (divide instead of multiply) for bulk shift output
  phys2cvr/phys2cvr.py
Labels: BugFIX

#30 Add output of all regression results for debug
  phys2cvr/phys2cvr.py
Labels: Minormod
